$(document).ready( function() { 

	//========== Global Variables  ==========================================================
	GLOBALS = new Array();
	range = "";
	datatype = "";
	banktxnarray = Array ( );                     // 1 dimensional array of banktxn_id s
	banktxntablearray = Array ( );                // 2 dimensional array used for populating table
	banktxntablerowarray = Array ( );             // 1 dimensional array of table row numbers keyed by banktxn_id
	banktxntablearraystatus = "initialload";
	activebanktxn_id = "";
	activebanktxntableindex = -1;
	activebanktxn_allocationbutton = "";		  // Confiem/Review/View/Allocate text on buttons
	updatelog = "";
	meTooIdArray = Array ( );                     // 1 dimensional array of banktxn_ids requested for duplicated allocation
	firstallocationmenupopulation = "1";
	favouriteaddedupdated = "";
	allocationclonearray = Array ( );              // 1 dimensional array of banktxn_ids suggested as allocation clones
	allocationclonetablearray = Array ( );         // 2 dimensional array used for populating table 
	oldallocationclonearraylength = 0;             // used to delete old table elements prior to refresh
	filtertype = Array( );
	filterparm0 = Array( );
	filterparm1 = Array( );
	filterparm2 = Array( );
	filtermaxindex = -1;
	wizardresponsearray = Array ( );               // 1 dimensional array of banktxn_ids generated by wizard
	wizardresponsetablearray = Array ( );          // 2 dimensional array used for populating table
	oldtxnfavourite_vatrateid = "";
	oldtxnfavourite_supplierid = "";
	oldtxnfavourite_paymenttype = "";
	oldtxnfavourite_fincategoryid = "";    
	oldtxnfavourite_customerid = "";
	oldtxnfavourite_jobid = "";
	
	xy = Array ( );
	// banktxnTableObject = "";
	
	//========== Main Routine  ==========================================================
	
	// alert("finallocate called");	
	
	bankorcash = document.getElementById("BankorCash").value;
	range = document.getElementById("Range").value;
	 
	// --------- setup dialogue popup ---------------------------------------
	$("#allocationDialog").dialog({
		autoOpen: false,
		width: "95%",
		height: "600",
		zindex: 25,
		overflow:"auto"
	});			 
	 
	$('#allocationDialogSave').on('click', function() {	
		updateFinalise();
		$("#allocationDialog").dialog("close");
	});	
	
	$('#allocationDialogClose').on('click', function() {	
		 $("#allocationDialog").dialog("close"); 
	});	
	 
	// --------- setup allocation clone popup ---------------------------------------
	$("#allocationCloneDialog").dialog({
		autoOpen: false,
		width: "95%",
		height: "auto",
		zindex: 25,
		overflow:"auto"
	});			 
	 
	$('#allocationCloneDialogSave').on('click', function() {	
		  updateCloneFinalise();
		  $("#allocationCloneDialog").dialog("close");
	});	
	
	$('#allocationCloneDialogClose').on('click', function() {	
		  $.alert({
			icon: 'fa fa-pencil text-success',
			title: "Allocations",
		    content: "Additional allocations cancelled."
		  })	
		  $("#allocationCloneDialog").dialog("close");
	});		
	
	 setupWait();
	 
	 
	//--------- newfavourite dialogue popup ---------------------------------------
	$("#newFavouriteDialog").dialog({ 
		autoOpen: false,
		width: "50%",
		height: "auto",
		zindex: 25,
		overflow:"auto"
	});			 
	 
	$('#newFavouriteDialogSave').on('click', function() {	
		newFavouriteAction();
	});	
	
	$('#newFavouriteDialogClose').on('click', function() {	
		$("#newFavouriteDialog").dialog("close");
	});	
	
	//--------- newsupplier dialogue popup ---------------------------------------
	$("#newSupplierDialog").dialog({
		autoOpen: false,
		width: "50%",
		height: "auto",
		zindex: 25,
		overflow:"auto"
	});			 
	 
	$('#newSupplierDialogSave').on('click', function() {	
		newSupplierAction();
	});	
	
	$('#newSupplierDialogCLose').on('click', function() {	
		$("#newSupplierDialog").dialog("close");
	});	   
	    
	//--------- newcustomer dialogue popup ---------------------------------------
	$("#newCustomerDialog").dialog({
		autoOpen: false,
		width: "50%",
		height: "auto",
		zindex: 25,
		overflow:"auto"
	});			 
	 
	$('#newCustomerDialogSave').on('click', function() {	
		newCustomerAction();
	});	
	
	$('#newCustomerDialogCLose').on('click', function() {	
		$("#newCustomerDialog").dialog("close");
	});	   
	
	//--------- newjob dialogue popup ---------------------------------------		
	$("#newJobDialog").dialog({
		autoOpen: false,
		width: "50%",
		height: "auto",
		zindex: 25,
		overflow:"auto"
	});			 
	 
	$('#newJobDialogSave').on('click', function() {	
		newJobAction();
	});	
	
	$('#newJobDialogCLose').on('click', function() {	
		$("#newJobDialog").dialog("close");
	});	   
		
	$("#wizardDialog").dialog({
		autoOpen: false,
		width: "95%",
		height: "auto",
		zindex: 25,
		overflow:"auto"
	});			 
	 
	$('#wizardDialogSave').on('click', function() {	
		$("#wizardDialog").dialog("close");
		uploadData("reload");
	});	
	
	$('#wizardDialogClose').on('click', function() {	
		$("#wizardDialog").dialog("close");
	});	  
	
	 //--------- add the dynamic listeners ---------------------------------------  
	 $('#wizpropose').on('click', function() {		 
		 callWizard("propose");
	 });	
	 $('#wizconfirm').on('click', function() {		 
		 callWizard("confirm");
	 });		
	 $('#wizreject').on('click', function() {		 
		 callWizard("reject");
	 });
	 $('#vatrateidinput').on('click', function() {		 
		 vatRateChanged();
	 });
	 $('#newfavouritebutton').on('click', function() {		 
		 favouriteaddedupdated = "Add"; 
		 newFavouriteOutput();
	 });	 
	 $('#newsupplierbutton').on('click', function() {		 
		 newSupplierOutput();
	 });		 
	 $('#newcustomerbutton').on('click', function() {		 
		 newCustomerOutput();
	 });		 
	 $('#newjobbutton').on('click', function() {		 
		 newJobOutput();
	 });	 
	 $('#moreorlesstext').on('click', function() {		 
		 moreOrLessToggle();
	 });		 
	 //--------- setup local hash database ---------------------------------------  
	 uploadData("initialload");
}); 
	
	
	
//========== Functions  ==========================================================

function uploadData() {
	function handleDataRequestSuccess(data, status) {
	    // alert(data);
		if(data != undefined){
			// $('#TRACETEXT').html(data); 
			Create_Hashes(data);
			companya = Get_Array_Hash('company');
			company_name = companya[0];
			Get_Data_Hash('company',company_name);
			createFilterArrays();  
			createBanktxnTableArray();
			// if (banktxntablearraystatus == "initialload") {populateBanktxnTable();} else {repopulateBanktxnTable();}
			populateBanktxnTable();
		}
		stopWait();	
	}		 
	
	function handleDataRequestFailure(xhr, reason, ex) {
		alert("Error Reason = "+"|"+xhr+"|"+reason+"|"+ex+"|");
		// messageAlert("Error Reason = "+"|"+xhr+"|"+reason+"|"+ex+"|");
	} 
	
	startWait("Loading");

	// range = range.replace(/\+/g, '%2B'); 
	banktxncriteria = "banktxn[fieldvalue=banktxn_processstatus:"+range+"]";
	var datarequestlist = "vatrate[mergedkey=vatrate_id+vatrate_dateeffective],company,fincategory,job,txntemplate,txnfavourite,customer,supplier,"+banktxncriteria;
	// alert(datarequestlist);
	var sUrl = JSSitePHPURL()+"/"+JSCodeVersion()+"_javascriptdataprovider.php"; 		 
	$.ajax({
	     url: sUrl,
	     data: { 
	    	 ServiceId: JSServiceId(),	        	
	    	 DomainId: JSDomainId(),
	    	 ModeId: JSModeId(),	        	
	    	 PersonId: JSPersonId(),	
	    	 SessionId: JSSessionId(),		        	
	    	 LoginModeId: JSLoginModeId(),
	    	 MenuId: JSMenuId(),
	    	 DataRequestList: datarequestlist
	     },
	     type: "GET",
	     dataType: "text",
	     timeout: 10000,
	     success: handleDataRequestSuccess,	        
	     error: handleDataRequestFailure
	});		 
	startWait("Loading"); 
}

function createBanktxnTableArray() {
// alert("createBanktxnTableArray called");
 banktxntablearray = Array ( );	
 banktxnarray = Get_Array_Hash('banktxn');	 
 if (banktxnarray.length >0) {
  for (banktxnindex in banktxnarray) {
   tbanktxn_id = banktxnarray[banktxnindex];
   Get_Data_Hash('banktxn',tbanktxn_id);
   if (GLOBALS['banktxn_processstatus'] == "submitted") {
    actiontext = "View";
    actionstatustext = "Submitted";
   }  
   if (GLOBALS['banktxn_processstatus'] == "raw") {
    actiontext = "Allocate";
    actionstatustext = "Not yet allocated";
   }
   if (GLOBALS['banktxn_processstatus'] == "proposed") {
	actiontext = "Confirm";
	actionstatustext = "Proposed as "+GLOBALS['banktxn_txnfavouriteid'];
   }   
   if (GLOBALS['banktxn_processstatus'] == "allocated") {
    actiontext = "Review";
    actionstatustext = "Allocated to "+GLOBALS['banktxn_txnfavouriteid'];
   }
   actionmetoo = "";
   banktxntablerowarray[tbanktxn_id] = banktxnindex;
   banktxntablearray[banktxnindex] = Array ( GLOBALS['banktxn_id'],
   GLOBALS['banktxn_date'],GLOBALS['banktxn_txntype'],Filter(GLOBALS['banktxn_description'],GLOBALS['banktxn_bankuploadid']),
   GLOBALS['banktxn_debit'],GLOBALS['banktxn_credit'],actiontext,actionmetoo,actionstatustext );
  }
 }
}

function populateBanktxnTable() {
	// alert("populateBanktxnTable called");
	var outtablearray = Array ();		    
    for (var bi in banktxntablearray) {
    	var outrowarray = Array ();
    	var temparray = banktxntablearray[bi];	
    	outrowarray.push(temparray[0]); // Id
    	outrowarray.push(temparray[1]); // Date
    	outrowarray.push(temparray[2]); // Type
    	outrowarray.push(temparray[3]); // Description
    	outrowarray.push(temparray[4]); // Debit
    	outrowarray.push(temparray[5]); // Credit
    	outrowarray.push('<button type="button" class="allocatebutton" id="allocatebutton_'+temparray[0]+'">'+temparray[6]+'</button>');
    	outrowarray.push('<input class="metoocheckbox" id="metoocheckbox_'+temparray[0]+'" type="checkbox" value="">'); // Me Too
    	outrowarray.push(temparray[8]); // Status
    	outtablearray.push(outrowarray); 
    };
    
    if ($.fn.dataTable.isDataTable('#banktxntable')) {
        $('#banktxntable').DataTable().clear().destroy(); 
        // alert("existing #banktxntable destroyed");
    }    
	
	$('#banktxntable').DataTable( {
    	scrollY:        '50vh',
        scrollCollapse: true,
        paging:         false,
        data: outtablearray,
        columnDefs: [
         {
            targets: '_all',
            defaultContent: '-'
         }
        ]
    } );	
	
	allocatebuttonListener();

}  

function allocatebuttonListener() {
	$('.allocatebutton').on('click', function() {
		var thisid = $(this).attr("id");
		var ida = thisid.split('_');
		activebanktxn_id = ida[1];
	    activebanktxn_allocationbutton = $(this).text();		
		activebanktxntablerow = $(this).closest('tr');  // CHECK
	    activebanktxntableindex = -1;     
	    tactivebanktxntableindex = -1;
	    for (banktxnindex in banktxnarray) {
	    	tactivebanktxntableindex++; 
	    	if (activebanktxn_id == banktxnarray[banktxnindex]) {activebanktxntableindex = tactivebanktxntableindex;}
	    }
	    showAllocationDialog();					
	});	
	
	$('.metoocheckbox').on('click', function() {
		// alert($(this).prop('checked'));
		var thisid = $(this).attr("id");
		var ida = thisid.split('_');
		var metoobanktxn_id = ida[1];
		meTooIdArray[metoobanktxn_id] = $(this).prop('checked');				
	});

}
	
function pulseBanktxnTable() {
// alert("pulseBanktxnTable called");	
// When row is allocated, pulse the color of the row yellow
var origColor = "#dd0";
var pulseColor = "#ff0";
/*
// Create a temp anim instance that nulls out when anim is complete
var rowColorAnim = new YAHOO.util.ColorAnim(activebanktxntablerow.cells, {
   backgroundColor:{to:origColor, from:pulseColor}, duration:2});
var onComplete = function() {
   rowColorAnim = null;
   YAHOO.util.Dom.setStyle(activebanktxntablerow.cells, "backgroundColor", "");
}
rowColorAnim.onComplete.subscribe(onComplete);
rowColorAnim.animate();
*/
}

function populateAllocationMenu() {
	 var aMenuDatastring = "";
	 aMenuDatastring = aMenuDatastring + '<ul id="allocationmenu">'; 
	 txntemplatearray = Get_Array_Hash('txntemplate');
	 txnfavouritearray = Get_Array_Hash('txnfavourite'); 
	 for (txntemplateindex in txntemplatearray) {
	  ttxntemplate_purpose = txntemplatearray[txntemplateindex]	 
	  Get_Data_Hash('txntemplate',ttxntemplate_purpose);
	  aMenuDatastring = aMenuDatastring +  '<li><div id="'+ttxntemplate_purpose + '_rootitem" style="color:navy;">' + ttxntemplate_purpose+'</div>';
	  aMenuDatastring = aMenuDatastring +  '<ul>';
	  for (txnfavouriteindex in txnfavouritearray) {
	   ttxnfavourite_id = txnfavouritearray[txnfavouriteindex]
	   Get_Data_Hash('txnfavourite',ttxnfavourite_id);	
	   if (GLOBALS['txnfavourite_purpose'] == ttxntemplate_purpose)  {
	    Get_Data_Hash('txnfavourite',ttxnfavourite_id);	
	    Get_Data_Hash('fincategory',GLOBALS['txnfavourite_fincategoryid']);
	    $usethis = "0";
	    if (GLOBALS["IOERROR"] == "0"){
	     if ((GLOBALS['fincategory_usedefaulted'] == "Yes")||(GLOBALS['fincategory_useselected'] == "Yes")) { $usethis = "1"; }	 
	     if (GLOBALS['fincategory_id'].substr(0,1) != "F") { $usethis = "0"; }
	     if (GLOBALS['fincategory_purpose'] != ttxntemplate_purpose) { $usethis = "0"; }	    
	     // if (GLOBALS['txnfavourite_purpose'] == "Dividend or Loan") {alert(ttxnfavourite_id+" "+GLOBALS['txnfavourite_fincategoryid']+" "+$usethis);} 
	     if ($usethis == "1") {
	 	  tbits = ttxnfavourite_id.split("_");  tfavouritename = tbits[1];
	 	  var ltxnfavourite_id = ttxnfavourite_id.replace(/ /g, "SPaCE");
		  aMenuDatastring = aMenuDatastring + '<li><div id="'+ltxnfavourite_id + '_item" style="color:navy;">'+tfavouritename+'</div></li>';
	     } 
	    }
	   }
	  }
	  if (GLOBALS['company_enablefullfavouritesallocate'] == "Yes") {
	   var ltxntemplate_purpose = ttxntemplate_purpose.replace(/ /g, "SPaCE")  
	   aMenuDatastring = aMenuDatastring + '<li><div id="'+ltxntemplate_purpose + '_newitem" style="color:purple;">..new ' + ttxntemplate_purpose + ' favourite</div></li>';
	  }
	  aMenuDatastring = aMenuDatastring + "</ul>";
	  aMenuDatastring = aMenuDatastring + "</li>";		  
	 }
	 aMenuDatastring = aMenuDatastring + "</ul>";		  
	 $('#favouriteallocations').html(aMenuDatastring);
	 $( "#allocationmenu" ).menu();
	 $( "#allocationmenu" ).css('border-width',2);
	 $( "#allocationmenu" ).css('border-color','navy');
	 
	 // ----- add listeners to allocation menu ---------------------------
	 txntemplatearray = Get_Array_Hash('txntemplate');
	 txnfavouritearray = Get_Array_Hash('txnfavourite'); 
	 for (txntemplateindex in txntemplatearray) {
	  ttxntemplate_purpose = txntemplatearray[txntemplateindex]	 
	  Get_Data_Hash('txntemplate',ttxntemplate_purpose);
	  for (txnfavouriteindex in txnfavouritearray) {
	   ttxnfavourite_id = txnfavouritearray[txnfavouriteindex]
	   Get_Data_Hash('txnfavourite',ttxnfavourite_id);	 	  
	   if (GLOBALS['txnfavourite_purpose'] == ttxntemplate_purpose)  {		
		var ltxnfavourite_id = ttxnfavourite_id.replace(/ /g, "SPaCE");   
		// alert("addListener "+ltxnfavourite_id+"_item");
		$('#'+ltxnfavourite_id+"_item").on('click', function() {
			// alert($(this).attr("id"));
			var thisid = $(this).attr("id");
			var ltxnfavourite_id = thisid.replace("_item", "");
			var ttxnfavourite_id = ltxnfavourite_id.replace(/SPaCE/g, " ");   
			// alert(ttxnfavourite_id);
			prepareInputFromFavourite(ttxnfavourite_id);
		});	
	   }
	  }
	  if (GLOBALS['company_enablefullfavouritesallocate'] == "Yes") {
		  var ltxntemplate_purpose = ttxntemplate_purpose.replace(/ /g, "SPaCE")  	  
	  	  $('#'+ltxntemplate_purpose+"_newitem").on('click', function() {
	  		  var thisid = $(this).attr("id");
			  var ltxntemplate_purpose = thisid.replace("_item", "");
			  var ttxntemplate_purpose = ltxntemplate_purpose.replace(/SPaCE/g, " ");   
			  // alert(ttxntemplate_purpose);
			  prepareInputFromFavourite(ttxntemplate_purpose);
		  });	
	  }	 
	}
}



function showAllocationDialog(e) {
 // alert("showAllocationDialog called - "+activebanktxn_allocationbutton+" "+activebanktxn_id);
 Get_Data_Hash('banktxn',activebanktxn_id);
 var actionN = ""; 
 if (activebanktxn_allocationbutton == "Confirm") { actionN = " - (Confirm)"; } 
 if (activebanktxn_allocationbutton == "Review") { actionN = " - (Review)"; }
 if (activebanktxn_allocationbutton == "View") { actionN = " - (View)"; }
 document.getElementById("allocationinput_header").innerHTML = "Transaction - "+activebanktxn_id+ actionN;
 document.getElementById("allocate_banktxn_date").innerHTML = GLOBALS['banktxn_date'];  
 document.getElementById("allocate_banktxn_txntype").innerHTML = GLOBALS['banktxn_txntype']; 
 document.getElementById("allocate_banktxn_description").innerHTML = GLOBALS['banktxn_description']; 
 document.getElementById("allocate_banktxn_debit").innerHTML = GLOBALS['banktxn_debit']; 
 document.getElementById("allocate_banktxn_credit").innerHTML = GLOBALS['banktxn_credit'];
 populateAllocationMenu();  
 $( "#allocationmenu" ).show();
 if (activebanktxn_allocationbutton == "Confirm") { prepareInputForReview(); } 
 if (activebanktxn_allocationbutton == "Review") { prepareInputForReview(); }
 if (activebanktxn_allocationbutton == "View") { prepareInputForReview(); }
 if (activebanktxn_allocationbutton == "Allocate") { initialiseInput(); }
 $("#allocationDialog").dialog("open"); 
}

function initialiseInput() {
 document.getElementById("allocationresult_message").innerHTML = "No Allocation made so far."; 	
 document.getElementById("purposerow").style.display = 'none'; 
 document.getElementById("favouritenamerow").style.display = 'none';
 document.getElementById("separator1row").style.display = 'none';  
 document.getElementById("supplieridrow").style.display = 'none'; 
 document.getElementById("paymenttyperow").style.display = 'none';  
 document.getElementById("vatrateidrow").style.display = 'none';
 document.getElementById("vatrow").style.display = 'none'; 
 document.getElementById("fincategoryidrow").style.display = 'none'; 
 document.getElementById("customeridrow").style.display = 'none';
 document.getElementById("separator2row").style.display = 'none'; 
 document.getElementById("commentrow").style.display = 'none';  
 document.getElementById("jobidrow").style.display = 'none';
}

function prepareInputForReview(e) {	
 // alert("prepareInputForReview called -" + activebanktxn_id);
 favouriteaddedupdated = "";
 document.getElementById("allocationresult_message").innerHTML = "Existing Allocation"; 	
 document.getElementById("idinput").value = activebanktxn_id;
 document.getElementById("purposeinput").value = GLOBALS['banktxn_purpose'];   
 document.getElementById("purposetext").innerHTML = GLOBALS['banktxn_purpose'];
 tbits = GLOBALS['banktxn_txnfavouriteid'].split("_");  tfavouritename = tbits[1]; 
 document.getElementById("favouritenametext").innerHTML = tfavouritename;
 temphash = Get_SelectArrays_Hash("supplier","supplier_id","supplier_name"); temphash[""] = ""; 
 JSINSELECTHASH(temphash,
	  document.allocateresultform.supplieridinput,GLOBALS['banktxn_supplierid'],"","","");
 JSINSELECTHASH(List2Hash("Transaction,Account"),
	  document.allocateresultform.paymenttypeinput,GLOBALS['banktxn_paymenttype'],"","","");
 JSINSELECTHASH(Get_SelectArrays_Hash_DateEffective("vatrate","vatrate_id","vatrate_description","banktxn_date"),
	  document.allocateresultform.vatrateidinput,GLOBALS['banktxn_vatrateid'],"No","","");
 Get_Data_Hash_DateEffective('vatrate',GLOBALS['banktxn_vatrateid'],GLOBALS['banktxn_date']);
 document.getElementById("vatratepercenttext").innerHTML = "@"+GLOBALS['vatrate_rate']+"%"; 
 document.getElementById("vatinput").value = GLOBALS['banktxn_vat'];
 JSINSELECTHASH(Get_FinCategorySelectArrays_Hash (GLOBALS['banktxn_purpose']),
	  document.allocateresultform.fincategoryidinput,GLOBALS['banktxn_fincategoryid'],"","","");
 temphash = Get_SelectArrays_Hash("customer","customer_id","customer_name"); temphash[""] = ""; 
 JSINSELECTHASH(temphash,
	  document.allocateresultform.customeridinput,GLOBALS['banktxn_customerid'],"","","");
 temphash = Get_SelectArrays_Hash("job","job_id","job_description"); temphash[""] = "none";
 JSINSELECTHASH(temphash,
	  document.allocateresultform.jobidinput,GLOBALS['banktxn_jobid'],"","","");
 document.getElementById("commentinput").value = GLOBALS['banktxn_comment'];
 document.getElementById("addtobankdescription").checked=false;    
 displayInput();
 oldtxnfavourite_vatrateid = GLOBALS['banktxn_vatrateid'];
 oldtxnfavourite_supplierid = GLOBALS['banktxn_supplierid'];  
 oldtxnfavourite_paymenttype = GLOBALS['banktxn_paymenttype'];   
 oldtxnfavourite_fincategoryid = GLOBALS['banktxn_fincategoryid'];    
 oldtxnfavourite_customerid = GLOBALS['banktxn_customerid'];
 oldtxnfavourite_jobid = GLOBALS['banktxn_jobid'];  
}

function prepareInputFromFavourite(parm) {
 // e, transactionfavouriteid	
 // alert("prepareInputFromFavourite called -" + parm);
 favouriteaddedupdated = "";
 if (activebanktxn_allocationbutton == "Confirm") { document.getElementById("allocationresult_message").innerHTML = "Confirmation of proposed allocation."; } 
 if (activebanktxn_allocationbutton == "Review") { document.getElementById("allocationresult_message").innerHTML = "Proposed update made to existing allocation."; }
 if (activebanktxn_allocationbutton == "Allocate") { document.getElementById("allocationresult_message").innerHTML = "Proposed update made to new allocation."; }  
 ttxnfavourite_id = parm;
 Get_Data_Hash('txnfavourite',ttxnfavourite_id);
 if (parm.indexOf("_newitem") != -1) {
  favouriteaddedupdated = "Add";
  document.getElementById("idinput").value = activebanktxn_id;
  tpurpose = ttxnfavourite_id.replace("_newitem","");
  document.getElementById("purposeinput").value = tpurpose;
  document.getElementById("purposetext").innerHTML = tpurpose;
  document.getElementById("favouritenametext").innerHTML = "";  
  GLOBALS['txnfavourite_supplierid'] = "";
  GLOBALS['txnfavourite_paymenttype'] = "";
  GLOBALS['txnfavourite_vatrateid'] = "";
  document.getElementById("vatratepercenttext").innerHTML = "";  
  document.getElementById("vatinput").value = "";  
  GLOBALS['txnfavourite_fincategoryid'] = "";
  GLOBALS['txnfavourite_customerid'] = "";
  GLOBALS['txnfavourite_comment'] = "";
  GLOBALS['txnfavourite_jobid'] = "";  
 } else {  
  favouriteaddedupdated = "";   
  tpurpose = GLOBALS['txnfavourite_purpose'];
  document.getElementById("idinput").value = activebanktxn_id;
  document.getElementById("purposeinput").value = tpurpose;   
  document.getElementById("purposetext").innerHTML = tpurpose;
  tbits = GLOBALS['txnfavourite_id'].split("_");  tfavouritename = tbits[1];   
  document.getElementById("favouritenametext").innerHTML = tfavouritename;
  document.getElementById("vatinput").value = calculateVAT(GLOBALS['banktxn_debit'],GLOBALS['banktxn_credit'],GLOBALS['txnfavourite_vatrateid'],GLOBALS['banktxn_date']);
  document.getElementById("vatratepercenttext").innerHTML = "@"+GLOBALS['vatrate_rate']+"%";        
 }
 temphash = Get_SelectArrays_Hash("supplier","supplier_id","supplier_name"); temphash[""] = "-- select supplier --"; 
 JSINSELECTHASH(temphash,
		  document.allocateresultform.supplieridinput,GLOBALS['txnfavourite_supplierid'],"","","");
 temphash = { 'Transaction':'Transaction', 'Account':'Account', '':'-- select payment type --'};
 JSINSELECTHASH(temphash,
		  document.allocateresultform.paymenttypeinput,GLOBALS['txnfavourite_paymenttype'],"","","");
 temphash = Get_SelectArrays_Hash_DateEffective("vatrate","vatrate_id","vatrate_description","banktxn_date"); temphash[""] = "-- select vat rate --";  
 JSINSELECTHASH(temphash,
		  document.allocateresultform.vatrateidinput,GLOBALS['txnfavourite_vatrateid'],"No","","");
 temphash = Get_FinCategorySelectArrays_Hash (tpurpose); temphash[""] = "-- select financial category --";   
 JSINSELECTHASH(temphash,
		  document.allocateresultform.fincategoryidinput,GLOBALS['txnfavourite_fincategoryid'],"","","");  
 temphash = Get_SelectArrays_Hash("customer","customer_id","customer_name"); temphash[""] = "-- select customer --"; 
 JSINSELECTHASH(temphash,
		  document.allocateresultform.customeridinput,GLOBALS['txnfavourite_customerid'],"","","");
 temphash = Get_SelectArrays_Hash("job","job_id","job_description"); temphash[""] = "none";
 JSINSELECTHASH(temphash,
		  document.allocateresultform.jobidinput,GLOBALS['txnfavourite_jobid'],"","","");
 document.getElementById("commentinput").value = GLOBALS['txnfavourite_comment']; 
 document.getElementById("addtobankdescription").checked=false;    
 displayInput();
 oldtxnfavourite_vatrateid = GLOBALS['txnfavourite_vatrateid'];
 oldtxnfavourite_supplierid = GLOBALS['txnfavourite_supplierid'];  
 oldtxnfavourite_paymenttype = GLOBALS['txnfavourite_paymenttype'];   
 oldtxnfavourite_fincategoryid = GLOBALS['txnfavourite_fincategoryid'];    
 oldtxnfavourite_customerid = GLOBALS['txnfavourite_customerid'];
 oldtxnfavourite_jobid = GLOBALS['txnfavourite_jobid']; 
 // alert(oldtxnfavourite_vatrateid+" "+oldtxnfavourite_supplierid+" "+oldtxnfavourite_paymenttype+" "+oldtxnfavourite_fincategoryid+" "+oldtxnfavourite_customerid+" "+oldtxnfavourite_jobid);
 if (favouriteaddedupdated == "Add") {newFavouriteOutput();}
}


function moreOrLessToggle() {
 var moreorless = document.getElementById("moreorlesstext").innerHTML;
 // alert("moreOrLessToggle called -" + moreorless);
 if (moreorless == "more detail...") { document.getElementById("moreorlesstext").innerHTML = "less detail..."; displayInput(); }
 else {
  if (moreorless == "less detail...") { document.getElementById("moreorlesstext").innerHTML = "more detail..."; displayInput(); }		
 }
}

function displayInput() {
 // purpose
 var tpurpose = document.getElementById("purposetext").innerHTML;	
 var moreorless = document.getElementById("moreorlesstext").innerHTML;
 // alert("displayInput called -" + tpurpose + " " + moreorless);

 var showall = "0";	 
 if (moreorless == "less detail...") { showall = "1"; }	 // this is opposite of next action.
 
 Get_Data_Hash('txntemplate',tpurpose);
 document.getElementById("purposerow").style.display = "table-row";
 
 if (GLOBALS['company_enablefullfavouritesallocate'] != "Yes") { document.getElementById("newfavouritebutton").style.display = 'none';}
 document.getElementById("favouritenamerow").style.display = "table-row";
 
 document.getElementById("separator1row").style.display = 'table-row';  
 
 if ((GLOBALS['company_showsupplierallocate'] == "No")||(GLOBALS['txntemplate_supplierid'] == "NA")||(GLOBALS['txntemplate_supplierid'] == "Defaulted")) {
  document.getElementById("supplieridrow").style.display = "none";
 }
 else {document.getElementById("supplieridrow").style.display = "table-row";}
 if ((showall == "1")&&(GLOBALS['txntemplate_supplierid'] != "NA")) {document.getElementById("supplieridrow").style.display = "table-row";}
 
 if ((GLOBALS['company_showpaymenttypeallocate'] == "No")||(GLOBALS['txntemplate_paymenttype'] == "NA")||(GLOBALS['txntemplate_paymenttype'] == "Defaulted")) {
  document.getElementById("paymenttyperow").style.display = "none";
 }
 else {document.getElementById("paymenttyperow").style.display = "table-row";}
 if ((showall == "1")&&(GLOBALS['txntemplate_paymenttype'] != "NA")) {document.getElementById("paymenttyperow").style.display = "table-row";}
 
 if ((GLOBALS['company_showvatallocate'] == "No")||(GLOBALS['txntemplate_vatrateid'] == "NA")||(GLOBALS['txntemplate_vatrateid'] == "Defaulted")) { 
  document.getElementById("vatrow").style.display = "none"; 	 
  document.getElementById("vatrateidrow").style.display = "none";
 } else {
  document.getElementById("vatrow").style.display = "table-row";  	 
  document.getElementById("vatrateidrow").style.display = "table-row" ;
 }
 if ((showall == "1")&&(GLOBALS['txntemplate_vatrateid'] != "NA")) {
  document.getElementById("vatrow").style.display = "table-row";  	 
  document.getElementById("vatrateidrow").style.display = "table-row" ;
 }
  
 if ((GLOBALS['company_showfincategoryallocate'] == "No")||(GLOBALS['txntemplate_fincategoryid'] == "NA")||(GLOBALS['txntemplate_fincategoryid'] == "Defaulted")) {
  document.getElementById("fincategoryidrow").style.display = "none";
 }
 else {document.getElementById("fincategoryidrow").style.display = "table-row";}
 if ((showall == "1")&&(GLOBALS['txntemplate_fincategoryid'] != "NA")) {document.getElementById("fincategoryidrow").style.display = "table-row";} 

 if ((GLOBALS['company_showcustomerallocate'] == "No")||(GLOBALS['txntemplate_customerid'] == "NA")||(GLOBALS['txntemplate_customerid'] == "Defaulted")) {
  document.getElementById("customeridrow").style.display = "none";}
 else {document.getElementById("customeridrow").style.display = "table-row";}
 if ((showall == "1")&&(GLOBALS['txntemplate_customerid'] != "NA")) {document.getElementById("customeridrow").style.display = "table-row";} 
 
 document.getElementById("separator2row").style.display = 'table-row'; 
 
 if ((GLOBALS['company_showcommentallocate'] == "No")||(GLOBALS['txntemplate_comment'] == "NA")||(GLOBALS['txntemplate_comment'] == "Defaulted")) {
  document.getElementById("commentrow").style.display = "none";
 } else {document.getElementById("commentrow").style.display = "table-row";}
 if ((showall == "1")&&(GLOBALS['txntemplate_comment'] != "NA")) {document.getElementById("commentrow").style.display = "table-row";}
 
 if ((GLOBALS['company_showjoballocate'] == "No")||(GLOBALS['txntemplate_jobid'] == "NA")||(GLOBALS['txntemplate_jobid'] == "Defaulted")) {
  document.getElementById("jobidrow").style.display = "none";
 } else {document.getElementById("jobidrow").style.display = "table-row";}
 if ((showall == "1")&&(GLOBALS['txntemplate_jobid'] != "NA")) {document.getElementById("jobidrow").style.display = "table-row";} 
 
 // alert("displayInput2 called -" + tpurpose); 
}

function updateFinalise() {
 // alert(activebanktxn_id+"   "+favouriteaddedupdated);  
 tfavouritename = document.getElementById("favouritenametext").innerHTML; 
 meTooIdArray[activebanktxn_id] = true;
 for (var banktxn_id in meTooIdArray) {
  if (meTooIdArray[banktxn_id]) { // if checked
   // alert(banktxn_id);
   Get_Data_Hash("banktxn",banktxn_id);
   Get_Data_Hash("txntemplate",document.getElementById("purposeinput").value);
   // alert("updateFinalise 2 -" + document.getElementById("purposeinput").value);
   GLOBALS['banktxn_processstatus'] = "allocated";
   GLOBALS['banktxn_purpose'] = document.getElementById("purposeinput").value; 
   // alert('banktxn_purpose'+GLOBALS['banktxn_purpose']); 
   GLOBALS['banktxn_txnfavouriteid'] = document.getElementById("purposetext").innerHTML+"_"+document.getElementById("favouritenametext").innerHTML;
   ts = document.getElementById("commentinput").value;
   if (ts != undefined){ GLOBALS['banktxn_comment'] = document.getElementById("commentinput").value;}
   else { GLOBALS['banktxn_comment'] = "";}
    
   ts = document.getElementById("addtobankdescription").checked;
   if (ts != undefined){
    if (document.getElementById("addtobankdescription").checked == true ) {
     var btbits = GLOBALS['banktxn_description'].split(" [");
     var origbanktxn_description = btbits[0] 
     GLOBALS['banktxn_description'] = origbanktxn_description + " [ "+GLOBALS['banktxn_comment']+" ]";
    }
   }  
   ts = document.getElementById("supplieridinput").value;
   if (ts != undefined){ GLOBALS['banktxn_supplierid'] = document.getElementById("supplieridinput").value; }
   else { GLOBALS['banktxn_supplierid'] = "";}
   ts = document.getElementById("paymenttypeinput").value;
   if (ts != undefined){ GLOBALS['banktxn_paymenttype'] = document.getElementById("paymenttypeinput").value; }
   else { GLOBALS['banktxn_paymenttype'] = "";} 
   ts = document.getElementById("vatrateidinput").value;
   if (ts != undefined){ GLOBALS['banktxn_vatrateid'] = document.getElementById("vatrateidinput").value;}
   else { GLOBALS['banktxn_vatrateid'] = "";}
   GLOBALS['banktxn_vat'] = calculateVAT(GLOBALS['banktxn_debit'],GLOBALS['banktxn_credit'],GLOBALS['banktxn_vatrateid'],GLOBALS['banktxn_date']); 
   ts = document.getElementById("fincategoryidinput").value;
   if (ts != undefined){ GLOBALS['banktxn_fincategoryid'] = document.getElementById("fincategoryidinput").value;}
   else { GLOBALS['banktxn_fincategoryid'] = "";}
   ts = document.getElementById("customeridinput").value;
   if (ts != undefined){ GLOBALS['banktxn_customerid'] = document.getElementById("customeridinput").value;}
   else { GLOBALS['banktxn_customerid'] = "";}
   ts = document.getElementById("jobidinput").value;
   if (ts != undefined){ GLOBALS['banktxn_jobid'] = document.getElementById("jobidinput").value;}
   else { GLOBALS['banktxn_jobid'] = "";}
   // alert("Pre Write - "+GLOBALS['banktxn_processstatus']+"/"+GLOBALS['banktxn_purpose']+"/"+GLOBALS['banktxn_txnfavouriteid']+"/"+GLOBALS['banktxn_supplierid']+"/"+GLOBALS['banktxn_customerid']);
   Write_Data_Hash("banktxn",banktxn_id);
     
   banktxntablerow = getBanktxnTableArrayRow(banktxn_id);
   // alert(banktxntablerow);
   if ( banktxntablerow  >= 0 ) {
	   var rowcontenta = $('#banktxntable').DataTable().row(banktxntablerow).data();
	   rowcontenta[3] = Filter(GLOBALS['banktxn_description'],GLOBALS['banktxn_bankuploadid']);
   	   var buttonhtml = '<button type="button" class="allocatebutton" id="allocatebutton_'+banktxn_id+'">Review</button>';
   	   rowcontenta[6] = buttonhtml; 
	   var checkboxhtml = '<input class="metoocheckbox" id="metoocheckbox_'+banktxn_id+'" type="checkbox" value="">'; // Me Too
	   rowcontenta[7] = checkboxhtml;
	   rowcontenta[8] = "allocated to "+GLOBALS['banktxn_txnfavouriteid']; 
	   $('#banktxntable').DataTable().row(banktxntablerow).data(rowcontenta).invalidate();
	   /*
	   $('#banktxntable').DataTable().cell({ row: banktxntablerow, column: 3 }).data(Filter(GLOBALS['banktxn_description'],GLOBALS['banktxn_bankuploadid'])).draw(); 
   	   var buttonhtml = '<button type="button" class="allocatebutton" id="allocatebutton_'+banktxn_id+'">Review</button>';
	   $('#banktxntable').DataTable().cell({ row: banktxntablerow, column: 6 }).data(buttonhtml).draw(); 
	   var checkboxhtml = '<input class="metoocheckbox" id="metoocheckbox_'+banktxn_id+'" type="checkbox" value="">'; // Me Too
	   $('#banktxntable').DataTable().cell({ row: banktxntablerow, column: 7 }).data(checkboxhtml).draw(); 		   
	   $('#banktxntable').DataTable().cell({ row: banktxntablerow, column: 8 }).data("allocated to "+GLOBALS['banktxn_txnfavouriteid']).draw(); 	   	   
	   */
	   
	   $('#allocatebutton_'+banktxn_id).closest('tr').addClass('selected');
   } 
  }  
 } 
 
 allocatebuttonListener();
 
 var r = true;
 if (favouriteaddedupdated == "Add") {
  var question = 'Do you want a new favourite "'+tfavouritename+'" to be created.';	
  var rejection = 'No new favourite created.';
  r=confirm(question);  
 } else {
  if ((GLOBALS['banktxn_vatrateid'] != oldtxnfavourite_vatrateid)&&((GLOBALS['txntemplate_vatrateid'] == "Defaulted")||(GLOBALS['txntemplate_vatrateid'] == "Selected"))) { 
   // alert("you have changed the vatrateid"); 
   favouriteaddedupdated = "Change"; 
  }
  if ((GLOBALS['banktxn_supplierid'] != oldtxnfavourite_supplierid)&&((GLOBALS['txntemplate_supplierid'] == "Defaulted")||(GLOBALS['txntemplate_supplierid'] == "Selected"))) { 
   // alert("you have changed the supplierid");
   favouriteaddedupdated = "Change"; 
  }
  if ((GLOBALS['banktxn_paymenttype'] != oldtxnfavourite_paymenttype)&&((GLOBALS['txntemplate_paymenttype'] == "Defaulted")||(GLOBALS['txntemplate_paymenttype'] == "Selected"))) { 
   // alert("you have changed the paymenttype");
   favouriteaddedupdated = "Change"; 
  }    
  if ((GLOBALS['banktxn_fincategoryid'] != oldtxnfavourite_fincategoryid)&&((GLOBALS['txntemplate_fincategoryid'] == "Defaulted")||(GLOBALS['txntemplate_fincategoryid'] == "Selected"))) { 
   // alert("you have changed the fincategoryid");
   favouriteaddedupdated = "Change"; 
  }    
  if ((GLOBALS['banktxn_customerid'] != oldtxnfavourite_customerid)&&((GLOBALS['txntemplate_customerid'] == "Defaulted")||(GLOBALS['txntemplate_customerid'] == "Selected"))) { 
   // alert("you have changed the customerid");
   favouriteaddedupdated = "Change"; 
  }
  if ((GLOBALS['banktxn_jobid'] != oldtxnfavourite_jobid)&&((GLOBALS['txntemplate_jobid'] == "Defaulted")||(GLOBALS['txntemplate_jobid'] == "Selected"))) { 
   // alert("you have changed the jobid");
   favouriteaddedupdated = "Change"; 
  }
  if (favouriteaddedupdated == "Change") {
	   var question = 'You have made changes to the allocation. Do you want existing favourite "'+tfavouritename+'" to be updated?';	 
	   var rejection = 'No changes made to favourite.';
		$.confirm({
			icon: 'fa fa-question-circle text-warning',
		    title: 'Update Favourite',
		    content: question,
		    buttons: {
		        somethingElse: {
		            text: 'Update Favourite',
		            btnClass: 'btn-blue',
		            action: function(){
		            	if ((favouriteaddedupdated == "Add")||(favouriteaddedupdated == "Change")) { txnFavouriteUpdate(); }
		            }
		        },
		        cancel: function () { 
		        	
		        },
		    }
		});	
	  }    
 }
  
 meTooIdArray = Array ( );

 // allocationDialogObject.hide();
 allocationclonearray = findPotentialAllocationClones(activebanktxn_id);
 if (allocationclonearray.length > 0) {
  $messagetext = "The following unallocated bank transactions have a matching description. <br><br>Do you wish to allocate them in the same way";
  $messagetext = $messagetext + " to <b>"  + document.getElementById("purposetext").innerHTML+"/"+document.getElementById("favouritenametext").innerHTML+"</b>\n";
  document.getElementById("allocationclonetext").innerHTML = $messagetext;
  populateAllocationCloneTable();
  $("#allocationCloneDialog").dialog("open");
  $('#allocationclonetable').DataTable().columns.adjust();  
 }
}

//========== Allocation Cloning  ==========================================================

function findPotentialAllocationClones(abanktxn_id) {
 // alert("findPotentialAllocationClones called - "+abanktxn_id);	
 foundarray = Array ( );
 Get_Data_Hash('banktxn',abanktxn_id);
 var abanktxn_description = Filter(GLOBALS['banktxn_description'],GLOBALS['banktxn_bankuploadid']);	
 sbanktxnarray = Get_Array_Hash('banktxn');
 if (sbanktxnarray.length >0) {
  for (sbanktxnindex in sbanktxnarray) {
   tbanktxn_id = sbanktxnarray[sbanktxnindex];
   Get_Data_Hash('banktxn',tbanktxn_id);
   
   if ((Match(abanktxn_description,Filter(GLOBALS['banktxn_description'],GLOBALS['banktxn_bankuploadid'])))
	    &&(tbanktxn_id != abanktxn_id)
	    &&(GLOBALS['banktxn_processstatus'] == "raw")) { 
	// alert(abanktxn_description+" = "+Filter(GLOBALS['banktxn_description'],GLOBALS['banktxn_bankuploadid']));   
    foundarray.push(tbanktxn_id); 
   }
  }
 }
 return foundarray;  
}

function populateAllocationCloneTable() {  
	// alert("populateAllocationCloneTable"); 
	if (allocationclonearray.length >0) {
	  for (allocationcloneindex in allocationclonearray) {
	   tbanktxn_id = allocationclonearray[allocationcloneindex];
	   Get_Data_Hash('banktxn',tbanktxn_id);
	   allocationclonetablearray[allocationcloneindex] = Array ( GLOBALS['banktxn_id'],
	   GLOBALS['banktxn_date'],GLOBALS['banktxn_txntype'],GLOBALS['banktxn_description'],
	   GLOBALS['banktxn_debit'],GLOBALS['banktxn_credit'] );
	  }
	 }
	 oldallocationclonearraylength = allocationclonearray.length; 				
	
	var outtablearray = Array ();		    
    for (var ai in allocationclonetablearray) {
    	var outrowarray = Array ();
    	var temparray = allocationclonetablearray[ai];	
    	outrowarray.push(temparray[0]); // Id
    	outrowarray.push(temparray[1]); // Date
    	outrowarray.push(temparray[2]); // Type
    	outrowarray.push(temparray[3]); // Description
    	outrowarray.push(temparray[4]); // Debit
    	outrowarray.push(temparray[5]); // Credit
    	outtablearray.push(outrowarray); 
    }

	// $('#TRACETEXT').html(outrowarray[0]+" "+outrowarray[1]+" "+outrowarray[2]); 
	// print_r(outtablearray);
    
    if ($.fn.dataTable.isDataTable('#allocationclonetable')) {
        $('#allocationclonetable').DataTable().clear().destroy(); 
        // alert("existing #banktxntable destroyed");
    }        
    
	$('#allocationclonetable').DataTable( {
    	scrollY:        '50vh',
        scrollCollapse: true,
        paging:         false,
        data: outtablearray,
        columnDefs: [
         {
            targets: '_all',
            defaultContent: '-'
         }
        ]
    } );	
}

function updateCloneFinalise() {
 //  alert("updateCloneFinalise called ");
 if (allocationclonearray.length >0) {
  for (allocationcloneindex in allocationclonearray) {
   banktxn_id = allocationclonearray[allocationcloneindex];
   Get_Data_Hash('banktxn',banktxn_id);
   Get_Data_Hash("txntemplate",document.getElementById("purposeinput").value);
   // alert("updateCloneFinalise -" + document.getElementById("purposeinput").value);
   GLOBALS['banktxn_processstatus'] = "allocated";
   GLOBALS['banktxn_purpose'] = document.getElementById("purposeinput").value;
   // alert('banktxn_purpose'+GLOBALS['banktxn_purpose']); 
   GLOBALS['banktxn_txnfavouriteid'] = document.getElementById("purposetext").innerHTML+"_"+document.getElementById("favouritenametext").innerHTML;
   // alert(GLOBALS['banktxn_txnfavouriteid']);   
   ts = document.getElementById("commentinput").value;
   if (ts != undefined){ GLOBALS['banktxn_comment'] = document.getElementById("commentinput").value;}
   else { GLOBALS['banktxn_comment'] = "";}
   ts = document.getElementById("supplieridinput").value;
   if (ts != undefined){ GLOBALS['banktxn_supplierid'] = document.getElementById("supplieridinput").value; }
   else { GLOBALS['banktxn_supplierid'] = "";}
   ts = document.getElementById("paymenttypeinput").value;
   if (ts != undefined){ GLOBALS['banktxn_paymenttype'] = document.getElementById("paymenttypeinput").value; }
   else { GLOBALS['banktxn_paymenttype'] = "";} 
   ts = document.getElementById("vatrateidinput").value;
   if (ts != undefined){ GLOBALS['banktxn_vatrateid'] = document.getElementById("vatrateidinput").value;}
   else { GLOBALS['banktxn_vatrateid'] = "";}
   GLOBALS['banktxn_vat'] = calculateVAT(GLOBALS['banktxn_debit'],GLOBALS['banktxn_credit'],GLOBALS['banktxn_vatrateid'],GLOBALS['banktxn_date']); 
   ts = document.getElementById("fincategoryidinput").value;
   if (ts != undefined){ GLOBALS['banktxn_fincategoryid'] = document.getElementById("fincategoryidinput").value;}
   else { GLOBALS['banktxn_fincategoryid'] = "";}
   ts = document.getElementById("customeridinput").value;
   if (ts != undefined){ GLOBALS['banktxn_customerid'] = document.getElementById("customeridinput").value;}
   else { GLOBALS['banktxn_customerid'] = "";}
   ts = document.getElementById("jobidinput").value;
   if (ts != undefined){ GLOBALS['banktxn_jobid'] = document.getElementById("jobidinput").value;}
   else { GLOBALS['banktxn_jobid'] = "";}
   // alert("Pre Write - "+GLOBALS['banktxn_processstatus']+"/"+GLOBALS['banktxn_purpose']+"/"+GLOBALS['banktxn_txnfavouriteid']+"/"+GLOBALS['banktxn_supplierid']+"/"+GLOBALS['banktxn_customerid']);   
   Write_Data_Hash("banktxn",banktxn_id);
   
   banktxntablerow = getBanktxnTableArrayRow(banktxn_id); // CHECK	   
   var buttonhtml = '<button type="button" class="allocatebutton" id="allocatebutton_'+banktxn_id+'">Review</button>';
   $('#banktxntable').DataTable().cell({ row: banktxntablerow, column: 6 }).data(buttonhtml).draw(); 
   var checkboxhtml = '<input class="metoocheckbox" id="metoocheckbox_'+banktxn_id+'" type="checkbox" value="">'; // Me Too
   $('#banktxntable').DataTable().cell({ row: banktxntablerow, column: 7 }).data(checkboxhtml).draw(); 		   
   $('#banktxntable').DataTable().cell({ row: banktxntablerow, column: 8 }).data("allocated to "+GLOBALS['banktxn_txnfavouriteid']).draw(); 	   	   
   activebanktxntablerow.addClass('selected'); // CHECK
  }
 } 
}

//========== Update Favourites  ==========================================================
	
function txnFavouriteUpdate() {
 alert("txnFavouriteUpdate -" + GLOBALS['banktxn_purpose'] + "  ===    " + GLOBALS['banktxn_txnfavouriteid']);
 Get_Data_Hash("txntemplate",GLOBALS['banktxn_purpose']);
 GLOBALS['txnfavourite_id'] = GLOBALS['banktxn_txnfavouriteid']; 
 GLOBALS['txnfavourite_purpose'] = GLOBALS['banktxn_purpose'];
 if (GLOBALS['txntemplate_supplierid'] == "NA") {GLOBALS['txnfavourite_supplierid'] = "";}
 else {GLOBALS['txnfavourite_supplierid'] = document.getElementById("supplieridinput").value;} 
 if (GLOBALS['txntemplate_paymenttype'] == "NA") {GLOBALS['txnfavourite_paymenttype'] = "";}
 else {GLOBALS['txnfavourite_paymenttype'] = document.getElementById("paymenttypeinput").value;} 
 if (GLOBALS['txntemplate_vatrateid'] == "NA") {GLOBALS['txnfavourite_vatrateid'] = "";}
 else {GLOBALS['txnfavourite_vatrateid'] = document.getElementById("vatrateidinput").value;} 
 if (GLOBALS['txntemplate_fincategoryid'] == "NA") {GLOBALS['txnfavourite_fincategoryid'] = "";}
 else {GLOBALS['txnfavourite_fincategoryid'] = document.getElementById("fincategoryidinput").value;} 
 if (GLOBALS['txntemplate_customerid'] == "NA") {GLOBALS['txnfavourite_customerid'] = "";}
 else {GLOBALS['txnfavourite_customerid'] = document.getElementById("customeridinput").value;} 
 if (GLOBALS['txntemplate_comment'] == "NA") {GLOBALS['txnfavourite_comment'] = "";}
 else {GLOBALS['txnfavourite_comment'] = document.getElementById("commentinput").value;} 
 if (GLOBALS['txntemplate_jobid'] == "NA") {GLOBALS['txnfavourite_jobid'] = "";}
 else {GLOBALS['txnfavourite_jobid'] = document.getElementById("jobidinput").value;} 
 Write_Data_Hash('txnfavourite',GLOBALS['txnfavourite_id']);
 tbits = GLOBALS['banktxn_txnfavouriteid'].split("_");  tfavouritename = tbits[1];     
 if (favouriteaddedupdated == "Add") { var acceptance = 'New favourite "'+tfavouritename+'" created.'; }	   	  
 else { var acceptance = 'Existing favourite "'+tfavouritename+'" changed.'; }	   
 // alert(acceptance);
 $.alert({
	icon: 'fa fa-lock text-success',
	title: "Update Favourite",
    content: acceptance
 });	
}

//========== New Data Routines  ==========================================================

function newFavouriteOutput() {
 document.getElementById("nffavouritepurposetext").innerHTML = "Transaction type: "+document.getElementById("purposetext").innerHTML;	 
 document.getElementById("nffavouritenameinput").value = "";
 $("#newFavouriteDialog").dialog("open");
}
function newSupplierOutput() {
 document.getElementById("nssupplieridinput").value = "";
 document.getElementById("nssuppliernameinput").value = ""; 
 $("#newSupplierDialog").dialog("open"); 
}
function newCustomerOutput() {
 document.getElementById("nccustomeridinput").value = "";
 document.getElementById("nccustomernameinput").value = ""	
 $("#newCustomerDialog").dialog("open"); 
}
function newJobOutput() {
 document.getElementById("njjobidinput").value = "";
 document.getElementById("njjobnameinput").value = ""	
 $("#newJobDialog").dialog("open"); 
}
function newFavouriteAction() {
 document.getElementById("favouritenametext").innerHTML = document.getElementById("nffavouritenameinput").value;
 $("#newFavouriteDialog").dialog("close"); 
}
function newSupplierAction() {
 Initialise_Data('supplier');
 newsupplier_id = document.getElementById("nssupplieridinput").value;
 GLOBALS['supplier_id'] = newsupplier_id;
 GLOBALS['supplier_name'] = document.getElementById("nssuppliernameinput").value;
 Write_Data_Hash("supplier",newsupplier_id);   
 $("#newSupplierDialog").dialog("close"); 
 temphash = Get_SelectArrays_Hash("supplier","supplier_id","supplier_name"); temphash[""] = ""; 
 JSINSELECTHASH(temphash,
		  document.allocateresultform.supplieridinput,newsupplier_id,"Yes","",""); 
}
function newCustomerAction() {
 Initialise_Data('customer');
 newcustomer_id = document.getElementById("nccustomeridinput").value;
 GLOBALS['customer_id'] = newcustomer_id;
 GLOBALS['customer_name'] = document.getElementById("nccustomernameinput").value;
 Write_Data_Hash("customer",newcustomer_id);
 $("#newCustomerDialog").dialog("close"); 
 temphash = Get_SelectArrays_Hash("customer","customer_id","customer_name"); temphash[""] = ""; 
 JSINSELECTHASH(temphash,
		 document.allocateresultform.customeridinput,newcustomer_id,"Yes","",""); 
}
function newJobAction() {
 Initialise_Data('job');
 newjob_id = document.getElementById("njjobidinput").value;
 GLOBALS['job_id'] = newjob_id;
 GLOBALS['job_name'] = document.getElementById("njjobnameinput").value;
 Write_Data_Hash("job",newjob_id);   
 $("#newJobDialog").dialog("close"); 
 temphash = Get_SelectArrays_Hash("job","job_id","job_name"); temphash[""] = ""; 
 JSINSELECTHASH(temphash,
			  document.allocateresultform.jobidinput,newjob_id,"Yes","",""); 
}

//========== Wizard Routines  ==========================================================

function callWizard(wizaction) {
	// alert("callWizard - "+wizaction);
	function handleWizardSuccess(data, status) {
	    // alert(data);
		// alert("The WizardSuccess handler was called; this transaction did not abort.  tId: " + o.tId + ".");
		if(data != undefined){
		   // $('#TRACETEXT').html(data); 
		   createWizardResponseTableArray(data);
		   populateWizardResponseTable();
		   $("#wizardDialog").dialog("open");
		   $('#wizardresponsetable').DataTable().columns.adjust();  		   
		}						
		stopWait();	
	}
	
	function handleWizardFailure(xhr, reason, ex) {
		alert("Error Reason = "+"|"+xhr+"|"+reason+"|"+ex+"|");
		// alert("Error Reason = "+"|"+xhr+"|"+reason+"|"+ex+"|");
	} 
	
	startWait("Loading");
	
	var sUrl = JSSitePHPURL()+"/"+JSCodeVersion()+"_finallocatewizard.php"; 		 
	$.ajax({
	     url: sUrl,
	     data: { 
	    	 ServiceId: JSServiceId(),	        	
	    	 DomainId: JSDomainId(),
	    	 ModeId: JSModeId(),	        	
	    	 PersonId: JSPersonId(),	
	    	 SessionId: JSSessionId(),		        	
	    	 LoginModeId: JSLoginModeId(),
	    	 MenuId: JSMenuId(),
	    	 WizAction: wizaction
	     },
	     type: "GET",
	     dataType: "text",
	     timeout: 100000,
	     success: handleWizardSuccess,	        
	     error: handleWizardFailure
	});			 
}

function createWizardResponseTableArray(responsetext) {
 // alert("createWizardResponseTable called ")+responsetext;
 document.getElementById("wizardopeningtext").innerHTML = "";
 document.getElementById("wizardclosingtext").innerHTML = "";
 wizardresponsearray = Array ( ); wizardresponsetablearray = Array ( );	 
 var responserecords = responsetext.split("^");
 var newindex = 0;
 for (var responserecordsindex in responserecords) {
  var responsesplit = responserecords[responserecordsindex].split("|"); 
  if (responsesplit[0] == "openingtext")	{document.getElementById("wizardopeningtext").innerHTML = responsesplit[1];}
  if (responsesplit[0] == "closingtext")	{document.getElementById("wizardclosingtext").innerHTML = responsesplit[1];}	
  if (responsesplit[0] == "data")	{
   wizardresponsearray[newindex] = responserecords[responserecordsindex];  	 
   wizardresponsetablearray[newindex] = Array ( responsesplit[1],
    responsesplit[2],responsesplit[3],responsesplit[4],responsesplit[5],responsesplit[6],responsesplit[7] );
   newindex++;
  }
 }
}

function populateWizardResponseTable() {		
	var outtablearray = Array ();		    
    for (var wi in wizardresponsetablearray) {
    	var outrowarray = Array ();
    	var temparray = wizardresponsetablearray[wi];	
    	outrowarray.push(temparray[0]); // Id
    	outrowarray.push(temparray[1]); // Date
    	outrowarray.push(temparray[2]); // Type
    	outrowarray.push(temparray[3]); // Description
    	outrowarray.push(temparray[4]); // Debit
    	outrowarray.push(temparray[5]); // Credit
    	outrowarray.push(temparray[6]); // Action
    	outtablearray.push(outrowarray);
    }
    
    if ($.fn.dataTable.isDataTable('#wizardresponsetable')) {
        $('#wizardresponsetable').DataTable().clear().destroy();               
    }
	
	$('#wizardresponsetable').DataTable( {
    	scrollY:        '50vh',
        scrollCollapse: true,
        paging:         false,
        data: outtablearray,
        columnDefs: [
         {
            targets: '_all',
            defaultContent: '-'
         }
        ]
    } );		 
}

//========== Utility Routines  ==========================================================

function getBanktxnTableArrayRow(tbanktxn_id) {
 // alert(tbanktxn_id);
 var data = $('#banktxntable').DataTable().rows().data();
 for (var rowindex in data) {
	 var rowcontenta = data[rowindex];
     if (tbanktxn_id == rowcontenta[0]) { 
    	 return rowindex;  
     }
 }
 return -1;
}

function calculateVAT(debitstr,creditstr,vatrateidstr,datestr) {
 var grossnum = parseFloat(debitstr)+ parseFloat(creditstr);
 Get_Data_Hash_DateEffective('vatrate',vatrateidstr,datestr);	
 var vatratenum = parseFloat(GLOBALS['vatrate_rate']);
 vatnum =grossnum - (grossnum /(1+(vatratenum/100)));
 var vatnumrounded = vatnum.toFixed(2);
 // alert(debitstr+"|"+creditstr+"|"+vatrateidstr+"|"+datestr+"|"+vatratenum.toString()+"|"+vatnumrounded.toString());
 return vatnumrounded.toString();
}

function vatRateChanged() {
 var newvatrateid = document.getElementById("vatrateidinput").value;
 document.getElementById("vatinput").value = calculateVAT(GLOBALS['banktxn_debit'],GLOBALS['banktxn_credit'],newvatrateid,GLOBALS['banktxn_date']);
 document.getElementById("vatratepercenttext").innerHTML = "@"+GLOBALS['vatrate_rate']+"%";    
}

function Get_FinCategorySelectArrays_Hash (purpose) {
 var thash = new Array();
 var tarray = Get_Array_Hash('fincategory');
 for (var tarrayindex in tarray) {
  var tkey = tarray[tarrayindex];
  Get_Data_Hash('fincategory',tkey);
  $usethis = "0";
  if (GLOBALS["IOERROR"] == "0"){
   if ((GLOBALS['fincategory_usedefaulted'] == "Yes")||(GLOBALS['fincategory_useselected'] == "Yes")) { $usethis = "1"; }	 
   if (GLOBALS['fincategory_id'].substr(0,1) != "F") { $usethis = "0"; }
   if (purpose != GLOBALS['fincategory_purpose']) { $usethis = "0"; }	    
   if ($usethis == "1") {
	$prefix = "";	   
    if (GLOBALS['fincategory_subheader'] == "Yes") { $prefix = "--------- "; }  	   
    thash[GLOBALS['fincategory_id']] = $prefix+GLOBALS['fincategory_description']; 	  
    // alert(GLOBALS[tkeyfield]+"==>"+GLOBALS[ttextfield]);
   }
  }
  else {alert("Get_FinCategorySelectArrays_Hash ERROR - "+tkey);}
 }
 return thash;
}

function Match (source, target) { 
 // input: strings to comnpare - output: true or false depending on allocation comparison rules
 var sourcea = source.replace(/ /g,"");
 var sourceb = sourcea.replace(/\./g,"");
 var sourcestr = sourceb;
 var sourcelen = sourcestr.length; 
 var targeta = target.replace(/ /g,"");	
 var targetb = targeta.replace(/\./g,"");
 var targetstr = targetb;
 var targetlen = targetstr.length;
 var maxlen = sourcelen;
 if (targetlen > sourcelen) { maxlen = targetlen; } 
 var sourcechar = "";  var targetchar = "";
 var matchedchars = 0; var unmatchedchars = 0;
 var matchmin = 10;
 if (GLOBALS['company_matchminallocate'] != "") {matchmin = parseFloat(GLOBALS['company_matchminallocate']);}
 var nomatchmax = 4;
 if (GLOBALS['company_nomatchmaxallocate'] != "") {nomatchmax = parseFloat(GLOBALS['company_nomatchmaxallocate']);} 
 for (var ci=0; ci<maxlen; ci++) { 
  if (ci > sourcelen) { sourcechar = "!";} else { sourcechar = sourcestr.substring(ci,1); } 
  if (ci > targetlen) { targetchar = "!";} else { targetchar = targetstr.substring(ci,1); } 
  if (sourcechar == targetchar) {matchedchars++;} else {unmatchedchars++;}  
 }
 var result = false;
 if ((matchedchars >= matchmin)||(unmatchedchars == 0)) {result = true;} 
 if (unmatchedchars > nomatchmax) {result = false;} 
 return result;
}	

function createFilterArrays () {
 var ichar = "";
 var section = "0";
 filtertype[0] = "";
 filterparm0[0] = ""; 
 filterparm1[0] = ""; 
 filterparm2[0] = ""; 
 var filterindex = 0;
 var parmindex = 0;
 // alert(GLOBALS['company_filteroutallocatelist']); 
 for (var ci=0; ci<GLOBALS['company_filteroutallocatelist'].length; ci++) { 	
  ichar = GLOBALS['company_filteroutallocatelist'].substring(ci,ci+1);
  if  ((ichar != "[")&&(ichar != "]")) { 
   if (section == "0") { 
    // prior to first parameter = Filter Type
    filtertype[filterindex] = filtertype[filterindex] + ichar;
    filtermaxindex = filterindex;
   }
   if (section == "1") { 
    // parameter text	   
    if (parmindex == 0) { filterparm0[filterindex] = filterparm0[filterindex] + ichar;  }	   
    if (parmindex == 1) { filterparm1[filterindex] = filterparm1[filterindex] + ichar;  }	
    if (parmindex == 2) { filterparm2[filterindex] = filterparm2[filterindex] + ichar;  }	    
   }		
   if (section == "2") { 
    // look for commas - which denote a new filter
    if (ichar == ",") {
     section = "0";         	
     filterindex++;
     filtertype[filterindex] = "";
     filterparm0[filterindex] = ""; 
     filterparm1[filterindex] = ""; 
     filterparm2[filterindex] = ""; 
     parmindex = 0;    	
    }
   }
  }
  if  (ichar == "[") { section = "1"; }
  if  (ichar == "]") { section = "2"; parmindex++; }	    
 }
 // var alertstr = "";
 // for (var fi=0; fi<=filtermaxindex; fi++) { 
 // alertstr = alertstr+filtertype[fi]+"*"+filterparm0[fi]+"*"+filterparm1[fi]+"*"+filterparm2[fi]+"^\n "; 
 // }  
 // alert(alertstr);   
}

function Filter (indescription,bankuploadid) {
 var outdescription = indescription;
 for (var fi=0; fi<=filtermaxindex; fi++) {
  var tdescription = "";
  if (filtertype[fi] == "HIDESECTION" ) {
   if ( filterparm0[fi] == bankuploadid ) {
    if (outdescription.indexOf(",") != -1) {
	 var fbitsa = outdescription.split(filterparm1[fi]);
     var fsep = "";
     var hideindex = parseInt(filterparm2[fi])-1;
     for (var fbitsai in fbitsa) {     
      if (fbitsai != hideindex) {
       tdescription = tdescription + fsep + fbitsa[fbitsai];
       fsep = filterparm1[fi];
      }
     }
     outdescription = tdescription;
    }
   }	  
  }
  if (filtertype[fi] == "HIDETEXT" ) {
   if ( filterparm0[fi] == bankuploadid ) { 
	tdescription = outdescription.replace(filterparm1[fi],filterparm2[fi]);
    outdescription = tdescription;		
   }
  } 
 } 
 return outdescription;	
}
